pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/etheshgaur/SeleniumAutomationProject.git'
            }
        }

        stage('Build & Test') {
            steps {
                bat 'mvn clean test -Dcucumber.filter.tags="@test"'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'target/**/*'
        }
    }
}